AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false
